include required(classpath("application"))

webservice {
  port = 8000
  interface = "0.0.0.0"
}

docker {
  hash-lookup {
    method = "local"
  }
}

database {
  profile = "slick.jdbc.PostgresProfile$"
  db {
    driver = "org.postgresql.Driver"
    url = "jdbc:postgresql://postgres:5432/cromwell"
    url = ${?CROMWELL_DATABASE_URL}
    user = "cromwell"
    user = ${?CROMWELL_DATABASE_USER}
    password = "cromwell"
    password = ${?CROMWELL_DATABASE_PASSWORD}
    connectionTimeout = 5000
  }
}

backend {
  default = "LocalDocker"

  providers {
    LocalDocker {
      actor-factory = "cromwell.backend.impl.sfs.config.ConfigBackendLifecycleActorFactory"

      config {
        concurrent-job-limit = 2
        run-in-background = true

        root = "/data/ai-bioworkflow-runner/executions"
        root = ${?CROMWELL_EXECUTIONS_ROOT}
        dockerRoot = "/data/ai-bioworkflow-runner/executions"
        dockerRoot = ${?CROMWELL_DOCKER_ROOT}

        runtime-attributes = """
          String? docker
          Int? cpu
          Float? memory
          String? disks
        """

        submit = """
          /usr/bin/env bash ${script}
        """

        submit-docker = """
          docker run --rm -i \
            --cidfile ${docker_cid} \
            -v ${cwd}:${docker_cwd} \
            -w ${docker_cwd} \
            ${docker} \
            ${job_shell} ${docker_script}
        """

        kill-docker = """
          docker kill $(cat ${docker_cid}) || true
        """

        filesystems {
          local {
            localization: [
              "hard-link",
              "copy"
            ]

            caching {
              duplication-strategy: [
                "hard-link",
                "copy"
              ]
              hashing-strategy: "file"
            }
          }
        }
      }
    }
  }
}
