#!/usr/bin/env bash
set -euo pipefail

log() {
	printf '[deploy] %s\n' "$*"
}

die() {
	printf '[deploy:error] %s\n' "$*" >&2
	exit 1
}

script_dir="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
if [[ -n "${AI_BIOWORKFLOW_DEPLOY_DIR:-}" ]]; then
	deploy_dir="$AI_BIOWORKFLOW_DEPLOY_DIR"
elif [[ -f "$script_dir/../docker-compose.prod.yml" ]]; then
	deploy_dir="$(cd "$script_dir/.." && pwd -P)"
else
	deploy_dir="$(pwd -P)"
fi

compose_file="${AI_BIOWORKFLOW_COMPOSE_FILE:-docker-compose.prod.yml}"
deploy_env_file="${AI_BIOWORKFLOW_DEPLOY_ENV_FILE:-.env.deploy}"
images_env_file="${AI_BIOWORKFLOW_IMAGES_ENV_FILE:-.env.images}"

compose_path="$deploy_dir/$compose_file"
deploy_env_path="$deploy_dir/$deploy_env_file"
images_env_path="$deploy_dir/$images_env_file"

[[ -d "$deploy_dir" ]] || die "Deploy directory not found: $deploy_dir"
[[ -f "$compose_path" ]] || die "Compose file not found: $compose_path"
[[ -f "$deploy_env_path" ]] || die "Deploy env file not found: $deploy_env_path"

read_env_value() {
	local file="$1"
	local name="$2"
	local value
	value="$(grep -E "^${name}=" "$file" | tail -n 1 | cut -d= -f2- | tr -d '\r' || true)"
	value="${value%\"}"
	value="${value#\"}"
	value="${value%\'}"
	value="${value#\'}"
	printf '%s' "$value"
}

runtime_env_file="$(read_env_value "$deploy_env_path" AI_BIOWORKFLOW_RUNTIME_ENV_FILE)"
runtime_env_file="${runtime_env_file:-./.env.prod}"
if [[ "$runtime_env_file" = /* ]]; then
	runtime_env_path="$runtime_env_file"
else
	runtime_env_path="$deploy_dir/${runtime_env_file#./}"
fi
[[ -f "$runtime_env_path" ]] || die "Runtime env file not found: $runtime_env_path"

validate_image_ref() {
	local name="$1"
	local value="$2"
	[[ -n "$value" ]] || die "$name is required"
	[[ "$value" != *[[:space:]]* ]] || die "$name must not contain whitespace"
}

validate_positive_integer() {
	local name="$1"
	local value="$2"
	[[ "$value" =~ ^[1-9][0-9]*$ ]] || die "$name must be a positive integer"
}

if [[ -n "${AI_BIOWORKFLOW_API_IMAGE:-}" || -n "${AI_BIOWORKFLOW_WEB_IMAGE:-}" ]]; then
	validate_image_ref AI_BIOWORKFLOW_API_IMAGE "${AI_BIOWORKFLOW_API_IMAGE:-}"
	validate_image_ref AI_BIOWORKFLOW_WEB_IMAGE "${AI_BIOWORKFLOW_WEB_IMAGE:-}"

	log "Writing $images_env_path"
	umask 077
	tmp_images_env="$(mktemp "${images_env_path}.tmp.XXXXXX")"
	{
		printf '# Generated by deploy/app/scripts/deploy-ecs.sh.\n'
		printf '# Do not edit by hand during automated deploys.\n\n'
		printf 'AI_BIOWORKFLOW_API_IMAGE=%s\n' "$AI_BIOWORKFLOW_API_IMAGE"
		printf 'AI_BIOWORKFLOW_WEB_IMAGE=%s\n' "$AI_BIOWORKFLOW_WEB_IMAGE"
	} > "$tmp_images_env"
	mv "$tmp_images_env" "$images_env_path"
elif [[ -f "$images_env_path" ]]; then
	log "Reusing existing $images_env_path"
else
	die "Set AI_BIOWORKFLOW_API_IMAGE and AI_BIOWORKFLOW_WEB_IMAGE, or create $images_env_path"
fi

compose=(docker compose --env-file "$deploy_env_path" --env-file "$images_env_path" -f "$compose_path")

log "Validating Compose configuration"
"${compose[@]}" config >/dev/null

log "Pulling images"
"${compose[@]}" pull

log "Starting services"
"${compose[@]}" up -d --remove-orphans

log "Current service status"
"${compose[@]}" ps

if [[ "${AI_BIOWORKFLOW_SKIP_HEALTHCHECK:-false}" == "true" ]]; then
	log "Skipping health checks"
	exit 0
fi

site_address="$(read_env_value "$deploy_env_path" AI_BIOWORKFLOW_SITE_ADDRESS)"
if [[ -n "$site_address" ]]; then
	if [[ "$site_address" == http://* || "$site_address" == https://* ]]; then
		public_base_url="${site_address%/}"
	else
		public_base_url="https://${site_address%/}"
	fi
else
	public_base_url=""
fi

health_url="${AI_BIOWORKFLOW_HEALTH_URL:-${public_base_url:+$public_base_url/health}}"
recipes_url="${AI_BIOWORKFLOW_RECIPES_URL:-${public_base_url:+$public_base_url/api/recipes}}"

check_url() {
	local label="$1"
	local url="$2"
	local attempts="${AI_BIOWORKFLOW_HEALTH_ATTEMPTS:-12}"
	local delay="${AI_BIOWORKFLOW_HEALTH_DELAY_SECONDS:-5}"
	local connect_timeout="${AI_BIOWORKFLOW_HEALTH_CONNECT_TIMEOUT_SECONDS:-5}"
	local max_time="${AI_BIOWORKFLOW_HEALTH_MAX_TIME_SECONDS:-15}"
	local attempt

	[[ -n "$url" ]] || die "No URL configured for $label health check"
	validate_positive_integer AI_BIOWORKFLOW_HEALTH_ATTEMPTS "$attempts"
	validate_positive_integer AI_BIOWORKFLOW_HEALTH_DELAY_SECONDS "$delay"
	validate_positive_integer AI_BIOWORKFLOW_HEALTH_CONNECT_TIMEOUT_SECONDS "$connect_timeout"
	validate_positive_integer AI_BIOWORKFLOW_HEALTH_MAX_TIME_SECONDS "$max_time"

	for attempt in $(seq 1 "$attempts"); do
		if curl --connect-timeout "$connect_timeout" --max-time "$max_time" -fsS "$url" >/dev/null; then
			log "$label health check passed: $url"
			return 0
		fi

		if [[ "$attempt" == "$attempts" ]]; then
			break
		fi
		log "$label health check not ready; retrying in ${delay}s ($attempt/$attempts)"
		sleep "$delay"
	done

	die "$label health check failed: $url"
}

check_url "API health" "$health_url"
check_url "API recipes" "$recipes_url"

log "Deploy completed"
